apiVersion: v1
kind: Service
metadata:
  name: aiohttp-log-ingestor
spec:
  selector:
    app: aiohttp-log-ingestor
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
