apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aiohttp-log-ingestor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aiohttp-log-ingestor
  minReplicas: 2
  maxReplicas: 7
  targetCPUUtilizationPercentage: 70
